#!/bin/bash
# chkconfig: 345 75 25
# description: XQBase Dynamic DNS Service

PID_FILE=/var/run/ddns.pid
case "$1" in
	start)
		/usr/share/java/bin/java -Xms16m -Xmx32m -jar /usr/local/xqbase-ddns/lib/ddns.jar &
		echo $! > $PID_FILE
		;;
	stop)
		read pid < $PID_FILE
		kill $pid
		rm $PID_FILE
		;;
esac